authors = ["emmett emmett@emmettboudreau.com"]
name = "LatheHE"
uuid = ""
version = "0.0.1"

[deps]
Lathe = "38d8eb38-e7b1-11e9-0012-376b6c802672"
Compose = "a81c6b42-2e10-5240-aca2-a61377ecd94b"
Hone = "12ccbac0-7b66-11ea-0cc2-7bbb5c90c0eb"
[compat]
julia = "1.4.0"
Lathe = "0.1.2"
